apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uav-flight-optimizer-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: uav-optimizer.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: routing-engine
                port:
                  number: 8000
          - path: /env-api
            pathType: Prefix
            backend:
              service:
                name: environment-service
                port:
                  number: 8081
